name: run get_stock_info.py

on:
  schedule:
    - cron: '0 18-21 * * 1-5'   # Every hour from 10:00 AM to 3:00 PM HKT (UTC 2:00 PM to 7:00 PM)
    - cron: '30 11 * * 1-5'     # At 3:30 PM HKT (UTC 7:30 PM)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run get_stock_info.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python get_stock_info.py

      - name: commit files
        run: |
          git config --local user.email "vincenman@github.com"
          git config --local user.name "vincenma"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          

     
